version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:80"
      - "8081:8081"
    links:
      - mongo
    volumes: 
      - .:/app
      - /app/node_modules
    command: npm run start:watch
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    expose: 
      - 27017