version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
