version: "2"
services:
  app:
    container_name: app
    image: node:alpine
    working_dir: /app
    restart: always
    ports:
      - "80:80"
    links:
      - mongo
    volumes: 
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm i && npm run start:watch"
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    expose: 
      - 27017